% Description: Finite burn using a ChemicalTank + ChemicalThruster -- BeginFiniteBurn / EndFiniteBurn bracket a propagation arc to model a long-duration burn.

Create Spacecraft Sat
Sat.DateFormat       = UTCGregorian
Sat.Epoch            = '01 Jan 2026 12:00:00.000'
Sat.CoordinateSystem = EarthMJ2000Eq
Sat.DisplayStateType = Cartesian
Sat.X                = 7100
Sat.Y                = 0
Sat.Z                = 1300
Sat.VX               = 0
Sat.VY               = 7.35
Sat.VZ               = 1
Sat.DryMass          = 850
Sat.Cd               = 2.2
Sat.Cr               = 1.8
Sat.DragArea         = 15
Sat.SRPArea          = 1
Sat.Tanks            = {tank1}
Sat.Thrusters        = {engine1}

Create ChemicalTank tank1
tank1.AllowNegativeFuelMass = false
tank1.FuelMass              = 725
tank1.Pressure              = 1200
tank1.Temperature           = 20
tank1.RefTemperature        = 12
tank1.Volume                = 0.8
tank1.FuelDensity           = 1029
tank1.PressureModel         = PressureRegulated

Create ChemicalThruster engine1
engine1.CoordinateSystem   = Local
engine1.Origin             = Earth
engine1.Axes               = VNB
engine1.ThrustDirection1   = 1
engine1.ThrustDirection2   = 0
engine1.ThrustDirection3   = 0
engine1.DutyCycle          = 1
engine1.ThrustScaleFactor  = 1
engine1.DecrementMass      = false
engine1.Tank               = {tank1}
engine1.MixRatio           = [1]
engine1.GravitationalAccel = 9.81
engine1.C1                 = 70
engine1.K1                 = 1500

Create ForceModel fm
fm.CentralBody = Earth
fm.PointMasses = {Earth}
fm.Drag        = None
fm.SRP         = Off

Create Propagator prop
prop.FM              = fm
prop.Type            = RungeKutta89
prop.InitialStepSize = 60
prop.Accuracy        = 1e-11
prop.MaxStep         = 2700

Create FiniteBurn fb
fb.Thrusters              = {engine1}
fb.ThrottleLogicAlgorithm = 'MaxNumberOfThrusters'

Create ReportFile RF
RF.Filename = 'finite_burn.txt'
RF.Add = {Sat.UTCGregorian, Sat.SMA, Sat.ECC, Sat.Energy}
RF.WriteHeaders = True

BeginMissionSequence

Propagate 'Prop 0.1 Days' prop(Sat) {Sat.ElapsedSecs = 8640}

BeginFiniteBurn 'Turn on Thruster' fb(Sat)

Propagate 'Prop 1 day' prop(Sat) {Sat.ElapsedDays = 1}

EndFiniteBurn 'Turn off Thruster' fb(Sat)

Propagate 'Prop 1 Day' prop(Sat) {Sat.ElapsedDays = 1}
