% Description: Finite burn using a ChemicalTank + ChemicalThruster -- BeginFiniteBurn / EndFiniteBurn bracket a propagation arc to model a long-duration burn.

Create Spacecraft Sc
Sc.DateFormat       = UTCGregorian
Sc.Epoch            = '01 Jan 2026 12:00:00.000'
Sc.CoordinateSystem = EarthMJ2000Eq
Sc.DisplayStateType = Cartesian
Sc.X                = 7100
Sc.Y                = 0
Sc.Z                = 1300
Sc.VX               = 0
Sc.VY               = 7.35
Sc.VZ               = 1
Sc.DryMass          = 850
Sc.Cd               = 2.2
Sc.Cr               = 1.8
Sc.DragArea         = 15
Sc.SRPArea          = 1
Sc.Tanks            = {tank1}
Sc.Thrusters        = {engine1}

Create ChemicalTank tank1
tank1.AllowNegativeFuelMass = false
tank1.FuelMass              = 725
tank1.Pressure              = 1200
tank1.Temperature           = 20
tank1.RefTemperature        = 12
tank1.Volume                = 0.8
tank1.FuelDensity           = 1029
tank1.PressureModel         = PressureRegulated

Create ChemicalThruster engine1
engine1.CoordinateSystem   = Local
engine1.Origin             = Earth
engine1.Axes               = VNB
engine1.ThrustDirection1   = 1
engine1.ThrustDirection2   = 0
engine1.ThrustDirection3   = 0
engine1.DutyCycle          = 1
engine1.ThrustScaleFactor  = 1
engine1.DecrementMass      = false
engine1.Tank               = {tank1}
engine1.MixRatio           = [1]
engine1.GravitationalAccel = 9.81
engine1.C1                 = 70
engine1.K1                 = 1500

Create ForceModel fm
fm.CentralBody = Earth
fm.PointMasses = {Earth}
fm.Drag        = None
fm.SRP         = Off

Create Propagator prop
prop.FM              = fm
prop.Type            = RungeKutta89
prop.InitialStepSize = 60
prop.Accuracy        = 1e-11
prop.MaxStep         = 2700

Create FiniteBurn fb
fb.Thrusters              = {engine1}
fb.ThrottleLogicAlgorithm = 'MaxNumberOfThrusters'

Create ReportFile RF
RF.Filename = 'finite_burn.txt'
RF.Add = {Sc.UTCGregorian, Sc.SMA, Sc.ECC, Sc.Energy}
RF.WriteHeaders = True

BeginMissionSequence

Propagate 'Prop 0.1 Days' prop(Sc) {Sc.ElapsedSecs = 8640}

BeginFiniteBurn 'Turn on Thruster' fb(Sc)

Propagate 'Prop 1 day' prop(Sc) {Sc.ElapsedDays = 1}

EndFiniteBurn 'Turn off Thruster' fb(Sc)

Propagate 'Prop 1 Day' prop(Sc) {Sc.ElapsedDays = 1}
