% Description: High-fidelity SRP using a SPAD spacecraft model file -- ForceModel.SRP.SRPModel = SPADFile.

Create Spacecraft aSpacecraft
aSpacecraft.DryMass            = 2000
aSpacecraft.SPADSRPFile        = '../data/vehicle/spad/SphericalModel.spo'
aSpacecraft.SPADSRPScaleFactor = 1

Create ForceModel aFM
aFM.SRP          = On
aFM.SRP.SRPModel = SPADFile

Create Propagator aProp
aProp.FM = aFM

Create ReportFile RF
RF.Filename = 'high_fidelity_srp.txt'
RF.Add = {aSpacecraft.UTCGregorian, aSpacecraft.X, aSpacecraft.Y, aSpacecraft.Z, aSpacecraft.SMA}
RF.WriteHeaders = True

BeginMissionSequence

Propagate aProp(aSpacecraft) {aSpacecraft.ElapsedDays = 0.2}
