% Description: Earth -> Moon transfer with DC-targeted lunar B-plane and lunar orbit insertion (LOI) burns; separate Earth-centered and Moon-centered force models.

Create Spacecraft Sat
Sat.DateFormat       = UTCGregorian
Sat.Epoch            = '22 Jul 2026 11:29:10.811'
Sat.CoordinateSystem = EarthMJ2000Eq
Sat.DisplayStateType = Cartesian
Sat.X                = -137380.1984338506
Sat.Y                = 75679.87867537055
Sat.Z                = 21487.63875187856
Sat.VX               = -0.2324532014235503
Sat.VY               = -0.4462753967758019
Sat.VZ               = 0.08561205662877103
Sat.DryMass          = 1000
Sat.Cd               = 2.2
Sat.Cr               = 1.7
Sat.DragArea         = 15
Sat.SRPArea          = 1

Create ForceModel AllForces
AllForces.CentralBody                      = Earth
AllForces.PrimaryBodies                    = {Earth}
AllForces.PointMasses                      = {Sun, Luna, Venus, Mars, Jupiter, Saturn, Uranus, Neptune}
AllForces.SRP                              = On
AllForces.ErrorControl                     = RSSStep
AllForces.GravityField.Earth.Degree        = 20
AllForces.GravityField.Earth.Order         = 20
AllForces.GravityField.Earth.PotentialFile = 'JGM2.cof'
AllForces.SRP.Flux                         = 1367
AllForces.Drag.AtmosphereModel             = MSISE90
AllForces.Drag.HistoricWeatherSource       = 'ConstantFluxAndGeoMag'
AllForces.Drag.PredictedWeatherSource      = 'ConstantFluxAndGeoMag'
AllForces.Drag.F107                        = 150
AllForces.Drag.F107A                       = 150
AllForces.Drag.MagneticIndex               = 3

Create ForceModel MoonAllForces
MoonAllForces.CentralBody                     = Luna
MoonAllForces.PrimaryBodies                   = {Luna}
MoonAllForces.PointMasses                     = {Sun, Earth, Venus, Mars, Jupiter, Saturn, Uranus, Neptune}
MoonAllForces.Drag                            = None
MoonAllForces.SRP                             = On
MoonAllForces.ErrorControl                    = RSSStep
MoonAllForces.GravityField.Luna.Degree        = 20
MoonAllForces.GravityField.Luna.Order         = 20
MoonAllForces.GravityField.Luna.PotentialFile = 'LP165P.cof'
MoonAllForces.SRP.Flux                        = 1367
MoonAllForces.SRP.SRPModel                    = Spherical

Create Propagator EarthFull
EarthFull.FM                       = AllForces
EarthFull.Type                     = RungeKutta89
EarthFull.InitialStepSize          = 60
EarthFull.Accuracy                 = 1e-11
EarthFull.MinStep                  = 0.001
EarthFull.MaxStep                  = 45000
EarthFull.MaxStepAttempts          = 50
EarthFull.StopIfAccuracyIsViolated = true

Create Propagator MoonFull
MoonFull.FM                       = MoonAllForces
MoonFull.Type                     = RungeKutta89
MoonFull.InitialStepSize          = 60
MoonFull.Accuracy                 = 1e-11
MoonFull.MinStep                  = 0.001
MoonFull.MaxStep                  = 15000
MoonFull.MaxStepAttempts          = 50
MoonFull.StopIfAccuracyIsViolated = true

Create ImpulsiveBurn TOI
TOI.CoordinateSystem = Local
TOI.Origin           = Earth
TOI.Axes             = VNB
TOI.Element1         = 0.14676929889
TOI.Element2         = 0.046042675892
TOI.Element3         = 0.090223244097

Create ImpulsiveBurn LOI
LOI.CoordinateSystem = Local
LOI.Origin           = Luna
LOI.Axes             = VNB
LOI.Element1         = -0.652
LOI.Element2         = 0
LOI.Element3         = 0

Create CoordinateSystem MoonMJ2000Eq
MoonMJ2000Eq.Origin = Luna
MoonMJ2000Eq.Axes   = MJ2000Eq

Create DifferentialCorrector DC1

Create ReportFile RF
RF.Filename = 'lunar_transfer.txt'
RF.Add = {Sat.UTCGregorian, Sat.Earth.RMAG, Sat.Luna.RMAG, Sat.Luna.SMA, Sat.Luna.ECC}
RF.WriteHeaders = True

BeginMissionSequence

Propagate 'Prop to Perigee' EarthFull(Sat) {Sat.Periapsis}

Target 'Target B-Plane' DC1 {SolveMode = Solve, ExitMode = DiscardAndContinue}
   Vary 'Vary TOI.V' DC1(TOI.Element1 = 0.14, {Perturbation = 1e-005, Lower = .13, Upper = .5, MaxStep = .01})
   Vary 'Vary TOI.B' DC1(TOI.Element3 = 0.1,  {Perturbation = 1e-005, Lower = -.5, Upper = .5, MaxStep = .01})
   Maneuver 'Apply TOI' TOI(Sat)
   Propagate 'Prop to Moon SOI' EarthFull(Sat) {Sat.Earth.RMAG = 325000, StopTolerance = 1e-005}
   Propagate 'Prop to Periselene' MoonFull(Sat) {Sat.Luna.Periapsis, StopTolerance = 1e-005}
   Achieve 'Achieve BdotT' DC1(Sat.MoonMJ2000Eq.BdotT = 15000.4401777, {Tolerance = 3})
   Achieve 'Achieve BdotR' DC1(Sat.MoonMJ2000Eq.BdotR = 4000.59308992, {Tolerance = 3})
EndTarget

Target 'Target Lunar Insertion' DC1 {SolveMode = Solve, ExitMode = DiscardAndContinue}
   Vary 'Vary LOI.V' DC1(LOI.Element1 = -0.65198120104, {Perturbation = 1e-003, Lower = -3, Upper = 0, MaxStep = .3})
   Maneuver 'Apply LOI' LOI(Sat)
   Achieve 'Achieve ECC = 0' DC1(Sat.Luna.ECC = 0, {Tolerance = 0.0001})
EndTarget

Propagate 'Prop 15 days' MoonFull(Sat) {Sat.ElapsedDays = 15}
